@startuml Splash_Components
skinparam componentStyle uml2

frame "Flask"{
    [CRUDMethod] ..> [Authenticator]: authenticate
    [CRUDMethod] ..> [PrivilegeChecker] :check
    [CRUDMethod] ..> [Validator]: validate
    [CRUDMethod] ..> [Mapper]: map data
    [Validator] ..> [JSONSchema]: validate
    [CRUDMethod] ..> [DAO]: persist
    
    [GlobusClient] 
}
[GlobusClient] ..> [GlobusAPI]
[Databroker] --> [NGINX]
[NGINX] ..> [uWSGI]: dispatch
[NGINX] ..> [StaticWeb]: serve
[uWSGI] ..> [CRUDMethod] : dispatch
[DAO] ..> [MongoDB] : insert
[MongoDB] ..> [Monstache]
[Monstache] ..> [Elasticsearch] : insert
[NGINX] ..> [Elasticsearch]: dispatch

@enduml

@startuml sample_deployment
skinparam componentStyle uml2

[Beamline] ..> [Databroker]
[Databroker] ..> [RESTBroker]
[RESTBroker] ..> [Splash]
[UserHub] ..> [Splash]
[User] ..> [Splash]

@enduml