@startuml
actor BU
activate BU

title In Situ - look at local run data < 1s
hide footbox

activate XiCAM
BU -> XiCAM:go()
XiCAM -> Bluesky: RunEngine(plan)
activate EpicsIOC
Bluesky -> EpicsIOC: caprotocol(run_params)
EpicsIOC -> Motors: move()
EpicsIOC -> Detector: start_imaging()
Detector -> EpicsIOC: stream_data()

EpicsIOC -> XiCAM: ca_callback(rawdata)
XiCAM -> BU: live_view(rawdata)
EpicsIOC -> Disk: write(data)
EpicsIOC -> Bluesky: ca_callbacks()
Bluesky -> DataBroker: consume(metadata, resources)
Bluesky -> XiCAM: callbacks(eventdata)
XiCAM -> BU: live_view(eventdata)
Bluesky -> XiCAM: plan_finished()
XiCAM -> BU: plan_finished()
Disk -> DTN: copy(data)
DTN -> "LTS": globus_transfer(resources)

' BU -> Disk: analyze_data()
deactivate EpicsIOC
deactivate XiCAM
@enduml

@startuml
actor BU

activate BCS
activate BU
title Post Hoc - Look at Run Data from Databroker >1s
hide footbox


BU -> BCS:go()
BCS -> Motors: move()
BCS -> Detector: start_imaging()


Detector -> Disk: write(data)
Disk -> DTN: copy(data)
DTN -> Globus: transfer(data)
BCS -> DataBroker: consume(metadata)
deactivate BCS

BU -> DataBroker: get_run_data()
return

deactivate BU
@enduml

@startuml
actor BU
activate BU
activate BCS
title Streaming - Look at Derived Data Quickly
hide footbox


BU -> BCS:go()
BCS -> Motors: move()
BCS -> Detector: start_imaging()


Detector -> Disk: write(data)
Disk -> DTN: copy(data)
DTN -> Globus: transfer(data)
activate NERSC
    Globus -> NERSC: transfer(data)
    NERSC -> NERSC: process_data(data)
    NERSC -> LTS: store(derived_data)
deactivate NERSC
BCS -> DataBroker: consume(metadata)
deactivate BCS

BU -> DataBroker: get_run_data()
return

BU -> LTS: request_derived_data()
return

deactivate BU
@enduml

@startuml
actor BU
title Data Flow: XPCS
hide footbox


BU -> "Xi-cam":go()
"Xi-cam" -> Bluesky:plan()
Bluesky -> "Motors IOC": move()
Bluesky -> "Detector IOC": trigger()
"Detector IOC" -> Disk: writeH5(data)
"Detector IOC" -> "Xi-cam": "CA callback(image)"
"Xi-cam" -> BU: Live feedback (raw)
"Detector IOC" -> Bluesky: "CA callback()"
Bluesky -> "Xi-cam": eventstream(docs)
"Xi-cam" -> BU: Live-ish feedback (events)
Bluesky -> Databroker: ingest(metadata, data)
"Xi-cam" -> NERSC_CAMLINK: do_workflow(run_uid)
NERSC_CAMLINK -> Databroker: get_event_stream(run_id)
NERSC_CAMLINK -> NERSC_CAMLINK: workflow(event_stream)
NERSC_CAMLINK -> "Xi-cam": callbacks()
NERSC_CAMLINK -> Databroker: ingest_derived(event_stream)
"Xi-cam" -> Databroker: query()
return runs
BU -> "Xi-cam": Open(run_uid)
"Xi-cam" -> "Databroker": query(run_uid)
return event_stream
"Xi-cam" -> BU: Late feedback (events)

deactivate BU
@enduml


@startuml

@enduml